apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tmux-workshop-admin
  namespace: workshop-tmux
  labels:
    app: tmux-workshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: tmux-workshop-sa
  namespace: workshop-tmux
