apiVersion: v1
kind: Service
metadata:
  name: tmux-workshop
  namespace: workshop-tmux
  labels:
    app: tmux-workshop
spec:
  selector:
    app: tmux-workshop
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
